// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pb/my_proto.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_pb_my_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_my_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_pb_my_proto_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	Age           int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Sex           string                 `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_pb_my_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_my_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_pb_my_proto_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloReply) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *HelloReply) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *HelloReply) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *HelloReply) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

var File_pb_my_proto_proto protoreflect.FileDescriptor

const file_pb_my_proto_proto_rawDesc = "" +
	"\n" +
	"\x11pb/my_proto.proto\x12\x04main\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"~\n" +
	"\n" +
	"HelloReply\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vphoneNumber\x18\x03 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\x12\x10\n" +
	"\x03sex\x18\x06 \x01(\tR\x03sex2\xab\x01\n" +
	"\bPingPong\x122\n" +
	"\bSayHello\x12\x12.main.HelloRequest\x1a\x10.main.HelloReply\"\x00\x127\n" +
	"\vStreamHello\x12\x12.main.HelloRequest\x1a\x10.main.HelloReply\"\x000\x01\x122\n" +
	"\x04Chat\x12\x12.main.HelloRequest\x1a\x10.main.HelloReply\"\x00(\x010\x01B\x05Z\x03pb/b\x06proto3"

var (
	file_pb_my_proto_proto_rawDescOnce sync.Once
	file_pb_my_proto_proto_rawDescData []byte
)

func file_pb_my_proto_proto_rawDescGZIP() []byte {
	file_pb_my_proto_proto_rawDescOnce.Do(func() {
		file_pb_my_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_my_proto_proto_rawDesc), len(file_pb_my_proto_proto_rawDesc)))
	})
	return file_pb_my_proto_proto_rawDescData
}

var file_pb_my_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_my_proto_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: main.HelloRequest
	(*HelloReply)(nil),   // 1: main.HelloReply
}
var file_pb_my_proto_proto_depIdxs = []int32{
	0, // 0: main.PingPong.SayHello:input_type -> main.HelloRequest
	0, // 1: main.PingPong.StreamHello:input_type -> main.HelloRequest
	0, // 2: main.PingPong.Chat:input_type -> main.HelloRequest
	1, // 3: main.PingPong.SayHello:output_type -> main.HelloReply
	1, // 4: main.PingPong.StreamHello:output_type -> main.HelloReply
	1, // 5: main.PingPong.Chat:output_type -> main.HelloReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_my_proto_proto_init() }
func file_pb_my_proto_proto_init() {
	if File_pb_my_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_my_proto_proto_rawDesc), len(file_pb_my_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_my_proto_proto_goTypes,
		DependencyIndexes: file_pb_my_proto_proto_depIdxs,
		MessageInfos:      file_pb_my_proto_proto_msgTypes,
	}.Build()
	File_pb_my_proto_proto = out.File
	file_pb_my_proto_proto_goTypes = nil
	file_pb_my_proto_proto_depIdxs = nil
}
